### ISSUE TITLE
DataFeed is not general, How to add a customized DataFeed in dAPI?

### ISSUE THREAD

**Issue by hujw77** [api3dao/airnode-protocol-v1#146]
https://github.com/api3dao/airnode-protocol-v1/blob/ab3be1c3dc486e5ee651ba9dfe2ce301b2421b1a/contracts/api3-server-v1/DataFeedServer.sol#L21-L24

**Comment by bbenligiray** [comment]
The DataFeedServer implementation includes the aggregation logic (median), in which case it makes sense for `value` to be numerical. We're okay with this lack of generality because we don't intend to provide non-numeric data feed services as API3, at least not with this contract.

If you wanted to use the contracts for a non-numerical use-case, I'd recommend you to copy over [BeaconUpdatesWithSignedData](https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/api3-server-v1/BeaconUpdatesWithSignedData.sol), update the `DataFeed` struct, remove `updateBeaconSetWithBeacons()`, `deriveBeaconSetId()`, `aggregateBeacons()` (or modify them if you want aggregation, but note that aggregating without any type assumption is difficult), modify `processBeaconUpdate()` so that `data` is not encoded `int224` but any arbitrary type. Then, you can operate an Airnode whose [signed data gateway](https://docs.api3.org/reference/airnode/latest/understand/http-gateways.html#http-signed-data-gateway) serves data that can update these data feeds.
