### ISSUE TITLE
Consider using functionCall() from Address.sol while fulfilling RRP requests

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode-protocol-v1#26]
We don't use functionCall() from Address.sol while fulfilling RRP requests due to future-proofness and gas cost optimization reasons. Consider this again.

**Comment by acenolaza** [comment]
The issue that I see with using the functions in Address.sol is the same we faced when using multicall() on [Multicall.sol](https://github.com/api3dao/airnode-protocol-v1/pull/21). These functions revert if the low level call does not succeed because they all end up calling [verifyCallResultFromTarget](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8d908fe2c20503b05f888dd9f702e3fa6fa65840/contracts/utils/Address.sol#L195)

**Comment by bbenligiray** [comment]
Good point. What about bubbling up the revert string, do you think that that would be worthwhile?

**Comment by bbenligiray** [comment]
This is mainly a question of how future-proof/chain-agnostic [this](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol#L236-L239) is

**Comment by bbenligiray** [comment]
If in doubt, leave it as is :man_shrugging:
